name: Run Tests

on:
  pull_request:
    branches: [devlopment, stable]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: checkout your repo
      - uses: actions/checkout@v4

      # Step 2: setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: install dependencies
      - run: npm install

      # Step 4: run tests
      - run: npm test
